apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: adminapp
  replicas: 1
  template:
    metadata:
      name: adminapp
      labels:
        app: adminapp
    spec:
      containers:
      - name: adminapp
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: aayush21/admin:beta
---
apiVersion: v1     
kind: Service
metadata:
  name: adminapp
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32679
  selector:
    app: adminapp
  type: NodePort
