apiVersion: apps/v1
kind: Deployment
metadata:
  name: authapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: authapp
  replicas: 1
  template:
    metadata:
      name: authapp
      labels:
        app: authapp
    spec:
      containers:
      - name: authapp
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_db
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host
        image: prasoon0459/auth_app:2.0.0
---
apiVersion: v1     
kind: Service
metadata:
  name: authapp
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8079
      targetPort: 8079
      nodePort: 32678
  selector:
    app: authapp
  type: NodePort
